import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {createApp} from '../src/server.mjs';
import {Store,redact} from '../src/store.mjs';
import {Engine,APIS} from '../src/engine.mjs';
import {Auth} from '../src/auth.mjs';
import {advise} from '../src/advisor.mjs';
const users=[{name:'defender',password:'defender-test-password-2026',role:'defender'},{name:'attacker',password:'attacker-test-password-2026',role:'attacker'}];
let app,base,def,atk,dir;
async function call(path,{token=def,body,method,headers={}}={}){const r=await fetch(base+path,{method:method||(body?'POST':'GET'),headers:{...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};}
async function poll(fn){for(let i=0;i<100;i++){const v=await fn();if(v)return v;await new Promise(r=>setTimeout(r,25));}throw Error('Timed out');}
async function configure(flags={}){const s=(await call('/state')).body.settings;return call('/settings',{body:{...s,...flags}});}
async function reset(api='orders'){await call('/authority',{body:{apiIds:[api],allowed:true}});await call('/actions',{body:{apiIds:[api],action:'reset'}});await configure({autoDetect:true,autoDecide:true,autoFix:true,continuous:false});}
before(async()=>{dir=mkdtempSync(join(tmpdir(),'sentinel-live-'));app=await createApp({dbPath:join(dir,'test.sqlite'),users,origins:['http://127.0.0.1:5173','http://127.0.0.1:5174']});base=await app.listen();def=(await call('/auth/login',{token:null,body:{username:users[0].name,password:users[0].password}})).body.token;atk=(await call('/auth/login',{token:null,body:{username:users[1].name,password:users[1].password}})).body.token;});
after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
test('unauthenticated control denied and attacker cannot grant authority',async()=>{assert.equal((await call('/state',{token:null})).status,401);assert.equal((await call('/authority',{token:atk,body:{apiIds:['orders'],allowed:true}})).status,403);});
test('exact CORS origins enforced',async()=>{assert.equal((await call('/state',{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await call('/state',{headers:{Origin:'http://127.0.0.1:5173'}})).status,200);});
test('all APIs initialized and OpenAPI has 144 operations',async()=>{assert.equal((await call('/state')).body.apis.length,24);const spec=(await call('/openapi.json')).body;assert.equal(Object.values(spec.paths).reduce((n,p)=>n+Object.keys(p).length,0),144);});
test('detected delete is blocked and authorized repair verified',async()=>{await reset();const r=await call('/lab/orders/objects/1',{token:atk,method:'DELETE',headers:{'X-Synthetic-Identity':'bob'}});assert.equal(r.status,403);const a=await poll(async()=>{const s=(await call('/state')).body.apis.find(a=>a.id==='orders');return s.secure&&!s.isolated?s:null;});assert.equal(a.recordCount,2);const state=(await call('/state')).body;const i=state.incidents.find(i=>i.id===r.body.body.incidentId);assert.equal(i.status,'repaired');assert.equal(i.repair.verification.passed,true);assert.equal(i.before.secure,false);assert.equal(i.after.secure,true);});
test('containment-only API is never changed',async()=>{await reset('profiles');await call('/authority',{body:{apiIds:['profiles'],allowed:false}});const before=(await call('/state')).body.apis.find(a=>a.id==='profiles');await call('/lab/profiles/objects/1',{token:atk,method:'DELETE',headers:{'X-Synthetic-Identity':'bob'}});await new Promise(r=>setTimeout(r,80));const after=(await call('/state')).body.apis.find(a=>a.id==='profiles');assert.equal(after.isolated,true);assert.equal(after.secure,false);assert.equal(after.revision,before.revision);assert.equal(after.recordCount,2);});
test('detection off permits real synthetic damage, history preserves before/after, manual recovery works',async()=>{await reset();await configure({autoDetect:false});const before=app.store.list('incident').length;const r=await call('/lab/orders/objects/1',{token:atk,method:'DELETE',headers:{'X-Synthetic-Identity':'bob'}});assert.equal(r.status,200);assert.equal(r.body.before.recordCount,2);assert.equal(r.body.after.recordCount,1);assert.equal(app.store.list('incident').length,before);const scan=await call('/scans',{body:{apiIds:['orders']}});assert.equal(scan.body.status,'completed');assert.ok(app.store.list('finding').some(f=>f.type==='data_loss'));const fix=await call('/actions',{body:{apiIds:['orders'],action:'repair'}});assert.equal(fix.body.results[0].verification.passed,true);});
test('decision switch and repair switch have independent effects',async()=>{await reset();await configure({autoDecide:false});await call('/lab/orders/objects/1',{token:atk,headers:{'X-Synthetic-Identity':'bob'}});let a=app.engine.api('orders');assert.equal(a.isolated,false);assert.equal(a.secure,false);await configure({autoDecide:true,autoFix:false});await call('/lab/orders/objects/1',{token:atk,headers:{'X-Synthetic-Identity':'bob'}});a=app.engine.api('orders');assert.equal(a.isolated,true);assert.equal(a.secure,false);});
test('queued automatic repair rechecks switches and authority',async()=>{const s=new Store(':memory:'),e=new Engine(s);e.authority(['orders'],true,'test');e.request('orders',{method:'DELETE',identity:'bob'},'test');e.authority(['orders'],false,'test');await new Promise(r=>setTimeout(r,100));assert.equal(e.api('orders').secure,false);assert.equal(e.api('orders').isolated,true);s.close();});
test('settings reject stale edits',async()=>{const s=(await call('/state')).body.settings;await call('/settings',{body:{...s,autoFix:false}});assert.equal((await call('/settings',{body:s})).status,409);});
test('SSE delivers persisted detection event without refresh',async()=>{await reset();await configure({autoFix:false});const after=app.store.latest(),abort=new AbortController();const stream=await fetch(base+'/events?after='+after,{headers:{Authorization:'Bearer '+def},signal:abort.signal});assert.equal(stream.status,200);const reader=stream.body.getReader();await reader.read();const request=await call('/lab/orders/objects/1',{token:atk,headers:{'X-Synthetic-Identity':'bob'}});assert.equal(request.status,403);let text='';for(let i=0;i<10&&!text.includes('incident.detected');i++){const r=await reader.read();text+=new TextDecoder().decode(r.value);}assert.match(text,/incident.detected/);abort.abort();});
test('attacker job sends actual HTTP, persists steps, and deduplicates retries',async()=>{await reset('invoices');const key=randomUUID();const first=await call('/attacks',{token:atk,body:{apiIds:['invoices'],scenario:'delete'},headers:{'Idempotency-Key':key}});const second=await call('/attacks',{token:atk,body:{apiIds:['invoices'],scenario:'delete'},headers:{'Idempotency-Key':key}});assert.equal(first.body.id,second.body.id);const job=await poll(()=>{const j=app.store.get('job',first.body.id);return j.status==='completed'?j:null;});assert.equal(job.requests,1);assert.equal(job.blocked,1);assert.equal(job.steps[0].method,'DELETE');});
test('missing authentication is detected as auth rather than BOLA',async()=>{await reset();await configure({autoFix:false});await call('/lab/orders/objects/1',{token:atk,headers:{'X-Synthetic-Identity':'anonymous'}});assert.equal(app.store.list('incident')[0].type,'auth');});
test('manual batch repair is all-or-nothing on authority validation',async()=>{await reset();await reset('profiles');await call('/authority',{body:{apiIds:['profiles'],allowed:false}});const rev=app.engine.api('orders').revision;assert.equal((await call('/actions',{body:{apiIds:['orders','profiles'],action:'repair'}})).status,403);assert.equal(app.engine.api('orders').revision,rev);});
test('unknown target and method rejected',async()=>{assert.equal((await call('/attacks',{body:{apiIds:['https://example.com'],scenario:'delete'}})).status,400);assert.equal((await call('/lab/orders/me',{method:'DELETE',token:atk})).status,405);});
test('SSE history cursor and database restart retain events and jobs',async()=>{const p=join(dir,'restart.sqlite');let s=new Store(p);s.put('job','x',{id:'x',actor:'attacker',status:'running'});s.event('example','orders','attacker',{x:1});s.close();s=new Store(p);const e=new Engine(s);assert.equal(s.get('job','x').status,'interrupted');assert.equal(s.events({after:0}).some(x=>x.type==='example'),true);assert.equal(e.view({role:'attacker',name:'attacker'}).jobs.length,1);s.close();});
test('bounded scan finds faults and secure scan is clean',()=>{const s=new Store(':memory:'),e=new Engine(s,{autoProcess:false});e.updateSettings({...e.settings(),autoDecide:false},'test');const first=e.scan(['orders'],'test');assert.equal(first.findings.length,4);e.authority(['orders'],true,'test');e.repair('orders','test');const secure=e.scan(['orders'],'test');assert.equal(secure.findings.length,0);const partial=e.scan(['orders'],'test',{budget:1});assert.equal(partial.status,'partial');s.close();});
test('all 24 sandbox APIs scanned within bounded budget',()=>{const s=new Store(':memory:'),e=new Engine(s,{autoProcess:false});const scan=e.scan(APIS,'test');assert.equal(scan.status,'completed');assert.equal(scan.requests,264);s.close();});
test('AI is advisory, rejects malformed output and removes unauthorized repair advice',async()=>{const inc={reason:'Owner mismatch',type:'bola',before:{secure:false}},api={repairAllowed:false};const fallback=await advise(inc,api,{key:null,model:null});assert.equal(fallback.provider,'local rules');const fake=async()=>new Response(JSON.stringify({output:[{content:[{type:'output_text',text:JSON.stringify({summary:'Review',actions:[{action:'repair',reason:'Fix'}],cautions:[]})}]}]}));const result=await advise(inc,api,{key:'fake-key',model:'test',fetcher:fake});assert.equal(result.provider,'OpenAI');assert.equal(result.actions[0].action,'request_authority');const bad=await advise(inc,api,{key:'fake',model:'test',fetcher:async()=>new Response('bad')});assert.equal(bad.provider,'local rules');});
test('reports never contain secrets or private fixture values',async()=>{const r=await call('/report');const text=JSON.stringify(r.body);assert.ok(!text.includes('SYNTHETIC-000-00-0000'));assert.ok(!text.includes(def));assert.equal(redact({password:'secret'}).password,'[REDACTED]');});
test('logout invalidates session',async()=>{const token=(await call('/auth/login',{token:null,body:{username:users[1].name,password:users[1].password}})).body.token;assert.equal((await call('/auth/logout',{token,body:{}})).status,200);assert.equal((await call('/state',{token})).status,401);});

test('imported definition constrains scans to registered declared object operations',async()=>{await reset();await configure({autoFix:false});assert.equal((await call('/spec/import',{body:{spec:'bad json'}})).status,400);const result=await call('/spec/import',{body:{spec:{openapi:'3.0.3',info:{title:'Order-only scope'},servers:[{url:'https://untrusted.invalid'}],paths:{'/lab/orders/objects/{id}':{get:{}},'/external':{get:{}}}}}});assert.deepEqual(result.body.scanApiIds,['orders']);const scan=await call('/scans',{body:{apiIds:['orders','profiles'],useImported:true}});assert.deepEqual(scan.body.apiIds,['orders']);assert.equal((await call('/scans',{body:{apiIds:['profiles'],useImported:true}})).status,400);assert.equal((await call('/scans',{body:{apiIds:['orders'],budget:0}})).status,400);});
test('credentials reject placeholder configuration and rotation revokes old sessions',async()=>{const s=new Store(':memory:'),auth=new Auth(s);await assert.rejects(()=>auth.provision('defender','REPLACE_WITH_A_STRONG_PASSWORD','defender'));await auth.provision('defender','old-secret-long-enough','defender');const login=await auth.login('defender','old-secret-long-enough','test');await auth.provision('defender','new-secret-long-enough','defender');assert.throws(()=>auth.user('Bearer '+login.token),/Session expired/);s.close();});

test('CI gate fails on confirmed findings and passes after verified repair',async()=>{await reset();await configure({autoDecide:false});const command=fileURLToPath(new URL('../src/ci-gate.mjs',import.meta.url));const env={...process.env,SENTINEL_URL:base,SENTINEL_USER:'defender',SENTINEL_PASSWORD:users[0].password,SENTINEL_APIS:'orders'};const run=()=>promisify(execFile)(process.execPath,[command],{env});await assert.rejects(run,e=>e.code===1&&e.stdout.includes('confirmedHighOrCritical'));await call('/actions',{body:{apiIds:['orders'],action:'repair'}});const result=await run();assert.match(result.stdout,/"confirmedHighOrCritical": 0/);env.SENTINEL_PASSWORD='wrong';await assert.rejects(run,e=>e.code===2);});
test('online SQLite backup preserves committed history',async()=>{const target=join(dir,'backup.sqlite'),command=fileURLToPath(new URL('../src/backup.mjs',import.meta.url));await promisify(execFile)(process.execPath,[command,target],{env:{...process.env,DATA_FILE:join(dir,'test.sqlite')}});const copy=new Store(target);assert.ok(copy.events({limit:1}).length);assert.equal(copy.latest(),app.store.latest());copy.close();});
