import { scrypt, randomBytes, timingSafeEqual, createHash } from 'node:crypto';
import { promisify } from 'node:util';
import { Fault } from './engine.mjs';
const derive=promisify(scrypt),digest=v=>createHash('sha256').update(v).digest('hex');
export class Auth {
 constructor(store){this.store=store;this.attempts=new Map();this.fallbackSalt=randomBytes(16).toString('hex');}
 async provision(name,password,role){if(!/^[a-zA-Z0-9._-]{3,64}$/.test(name)||typeof password!=='string'||password.length<16||password.length>256||/REPLACE_WITH|CHANGE_ME/i.test(password))throw new Error('Usernames must be 3–64 safe characters and passwords 16–256 characters');const old=this.store.db.prepare('SELECT * FROM users WHERE name=?').get(name);const salt=old?.salt||randomBytes(16).toString('hex'),hash=Buffer.from(await derive(password,salt,64)).toString('hex');if(old&&(old.hash!==hash||old.role!==role))this.store.db.prepare('DELETE FROM sessions WHERE name=?').run(name);this.store.db.prepare('INSERT INTO users VALUES(?,?,?,?) ON CONFLICT(name) DO UPDATE SET role=excluded.role,salt=excluded.salt,hash=excluded.hash').run(name,role,salt,hash);}
 async login(name,password,ip){if(typeof name!=='string'||typeof password!=='string'||name.length>64||password.length>256)throw new Fault(400,'Invalid login input');const key=ip+':'+name,t=Date.now(),list=(this.attempts.get(key)||[]).filter(x=>t-x<900000);if(list.length>=8)throw new Fault(429,'Too many attempts. Wait 15 minutes.');list.push(t);this.attempts.set(key,list);if(this.attempts.size>5000)this.attempts.clear();const u=this.store.db.prepare('SELECT * FROM users WHERE name=?').get(name),hash=Buffer.from(await derive(password,u?.salt||this.fallbackSalt,64));if(!u||!timingSafeEqual(hash,Buffer.from(u.hash,'hex')))throw new Fault(401,'Invalid username or password');this.attempts.delete(key);const token=randomBytes(32).toString('base64url'),expires=Date.now()+4*3600000;this.store.db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());this.store.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(token),name,expires);return {token,expires,user:{name:u.name,role:u.role}};}
 user(header){if(!header?.startsWith('Bearer ')||header.length>150)throw new Fault(401,'Sign in to continue');const hash=digest(header.slice(7)),u=this.store.db.prepare('SELECT u.name,u.role,s.expires FROM sessions s JOIN users u ON u.name=s.name WHERE s.hash=? AND s.expires>?').get(hash,Date.now());if(!u)throw new Fault(401,'Session expired. Sign in again.');return {...u,sessionHash:hash};}
 logout(user){this.store.db.prepare('DELETE FROM sessions WHERE hash=?').run(user.sessionHash);}
}
