import { randomUUID } from 'node:crypto';
import { redact } from './store.mjs';
export const APIS=['orders','profiles','invoices','payments','shipping','inventory','support','subscriptions','analytics','exports','documents','projects','billing','refunds','bookings','messages','devices','teams','rewards','contracts','reports','notifications','vendors','audit'];
export const SCENARIOS=['bola','delete','exposure','auth','rate','chain','legitimate'];
export const now=()=>new Date().toISOString();
export class Fault extends Error {constructor(status,message){super(message);this.status=status;}}
export function ids(value){if(!Array.isArray(value)||!value.length||value.length>24||value.some(x=>!APIS.includes(x)))throw new Fault(400,'Select registered sandbox APIs');return [...new Set(value)];}
export function seed(api){return ['1','2'].map((id,i)=>({id,owner_id:i?'bob':'alice',label:`${i?'Bob':'Alice'} synthetic ${api}`,related:{api:APIS[(APIS.indexOf(api)+1)%24],id},private:{ssn:'SYNTHETIC-000-00-0000',api_key:'FAKE-LAB-KEY',internal_notes:'Private synthetic note'}}));}
const DEFAULT={autoDetect:true,autoDecide:true,autoFix:true,continuous:false,intervalSeconds:120,scanIds:['orders'],version:1};
export class Engine {
 constructor(store,{autoProcess=true}={}){this.store=store;this.autoProcess=autoProcess;this.rates=new Map();this.pending=new Set();this.timers=new Map();this.scanRunning=false;
   for(const id of APIS)if(!store.get('api',id))store.put('api',id,{id,name:id[0].toUpperCase()+id.slice(1),repairAllowed:false,isolated:false,secure:false,revision:1,records:seed(id),updatedAt:now()});
   if(!store.get('settings','main'))store.put('settings','main',DEFAULT);
   for(const job of store.list('job',10000))if(['queued','running'].includes(job.status)){job.status='interrupted';job.finishedAt=now();store.put('job',job.id,job);store.event('simulation.interrupted','',job.actor,{jobId:job.id,reason:'Server restarted. Explicit replay is required; destructive steps are never blindly repeated.'});}
   for(const scan of store.list('scan',1000))if(scan.status==='running'){scan.status='interrupted';store.put('scan',scan.id,scan);}
 }
 close(){for(const t of this.timers.values())clearTimeout(t);this.timers.clear();}
 settings(){return this.store.get('settings','main');}
 api(id){const a=this.store.get('api',id);if(!a)throw new Fault(404,'Unknown sandbox API');return a;}
 summary(a){return {id:a.id,name:a.name,repairAllowed:a.repairAllowed,isolated:a.isolated,secure:a.secure,revision:a.revision,recordCount:a.records.length,updatedAt:a.updatedAt,dependsOn:a.records[0]?.related.api||APIS[(APIS.indexOf(a.id)+1)%24]};}
 save(a){a.updatedAt=now();this.store.put('api',a.id,a);}
 updateSettings(input,actor){const current=this.settings();if(input.version!==current.version)throw new Fault(409,'Settings changed in another dashboard. Reload and try again.');const next={...current};for(const k of ['autoDetect','autoDecide','autoFix','continuous'])if(k in input){if(typeof input[k]!=='boolean')throw new Fault(400,k+' must be boolean');next[k]=input[k];}if('intervalSeconds'in input){if(!Number.isInteger(input.intervalSeconds)||input.intervalSeconds<30||input.intervalSeconds>3600)throw new Fault(400,'Scan interval must be 30–3600 seconds');next.intervalSeconds=input.intervalSeconds;}if('scanIds'in input)next.scanIds=ids(input.scanIds);next.version++;this.store.put('settings','main',next);this.store.event('policy.updated','',actor,{before:current,after:next});return next;}
 authority(apiIds,allowed,actor){if(typeof allowed!=='boolean')throw new Fault(400,'allowed must be boolean');for(const id of ids(apiIds)){const a=this.api(id),before=this.summary(a);a.repairAllowed=allowed;this.save(a);this.store.event('authority.updated',id,actor,{before,after:this.summary(a)});}}
 backend(a,{method='GET',resource='objects',id='1',identity='alice',rateKey='live',ignoreRate=false}={}){
   if(resource==='health')return {status:200,body:{ok:true}};
   if(a.secure&&!['alice','bob'].includes(identity))return {status:401,body:{error:'Authentication required'}};
   if(a.secure&&!ignoreRate){const key=a.id+':'+identity+':'+rateKey,t=Date.now(),recent=(this.rates.get(key)||[]).filter(x=>t-x<1000);if(recent.length>=5)return {status:429,body:{error:'Rate limit enforced'}};recent.push(t);this.rates.set(key,recent);if(this.rates.size>5000)this.rates.clear();}
   if(resource==='me')return {status:200,body:{id:identity||'anonymous',role:'user'}};
   const visible=r=>a.secure?Object.fromEntries(Object.entries(r).filter(([k])=>k!=='private')):r;
   if(resource==='list')return {status:200,body:{items:a.records.filter(r=>!a.secure||r.owner_id===identity).map(visible)}};
   const r=a.records.find(r=>r.id===id);if(!r)return {status:404,body:{error:'Synthetic resource missing'}};
   if(a.secure&&r.owner_id!==identity)return {status:403,body:{error:'Resource ownership denied'}};
   if(method==='DELETE'){a.records=a.records.filter(r=>r.id!==id);return {status:200,body:{deleted:id,owner_id:r.owner_id}};}
   return {status:200,body:visible(r)};
 }
 threat(a,request,response){if(request.resource==='health')return null;const identity=request.identity,owner=request.id==='1'?'alice':request.id==='2'?'bob':null;
   if(!['alice','bob'].includes(identity))return {type:'auth',severity:'High',reason:'An unauthenticated identity requested a private resource.'};
   if(owner&&owner!==identity&&['objects','search'].includes(request.resource))return {type:request.method==='DELETE'?'destructive_attempt':'bola',severity:request.method==='DELETE'?'Critical':'High',reason:`${identity} attempted ${request.method} on ${owner}'s object ${request.id}.`};
   if(response?.status===200&&(response.body.private||response.body.items?.some(r=>r.private||r.owner_id!==identity)))return {type:'exposure',severity:'High',reason:'The upstream response includes prohibited private fields or foreign-owned records.'};
   return null;
 }
 incident(apiId,threat,request,actor,{source='gateway',impact='Prevented: the gateway withheld the request or response.'}={}){
   const a=this.api(apiId),id=randomUUID(),s=this.settings();const inc={id,apiId,type:threat.type,severity:threat.severity,reason:threat.reason,source,actor,detectedAt:now(),status:'detected',impact,request:redact(request),before:this.summary(a),after:null,policy:{autoDetect:s.autoDetect,autoDecide:s.autoDecide,autoFix:s.autoFix,repairAllowed:a.repairAllowed},timeline:[],advice:null};
   inc.timeline.push({time:now(),stage:'detected',detail:threat.reason});this.store.put('incident',id,inc);this.store.event('incident.detected',apiId,actor,{incidentId:id,type:inc.type,severity:inc.severity,before:inc.before,impact});
   if(s.autoDecide){a.isolated=true;this.save(a);inc.status='isolated';inc.timeline.push({time:now(),stage:'isolated',detail:'Gateway forwarding stopped. Backend mutation authority is checked separately.'});inc.after=this.summary(a);this.store.put('incident',id,inc);this.store.event('api.isolated',apiId,actor,{incidentId:id,before:inc.before,after:inc.after});
     if(s.autoFix&&a.repairAllowed&&this.autoProcess&&!this.pending.has(apiId)){this.pending.add(apiId);const timer=setTimeout(()=>{try{const p=this.settings();if(p.autoDetect&&p.autoDecide&&p.autoFix&&this.api(apiId).revision===inc.before.revision)this.repair(apiId,'automatic',id);else this.store.event('repair.deferred',apiId,'system',{incidentId:id,reason:'Automation was disabled before repair commit'});}catch(e){this.store.event('repair.failed',apiId,'system',{incidentId:id,error:e.message});}finally{this.pending.delete(apiId);this.timers.delete(apiId);}},50);timer.unref();this.timers.set(apiId,timer);}
   }else{inc.status='awaiting_decision';inc.after=this.summary(a);inc.timeline.push({time:now(),stage:'awaiting_decision',detail:'Current malicious request is blocked. API-wide isolation and repair await an operator.'});this.store.put('incident',id,inc);}
   return inc;
 }
 request(apiId,req,actor){const a=this.api(apiId),before=this.summary(a),s=this.settings();const request={method:req.method||'GET',resource:req.resource||'objects',id:req.id||'1',identity:req.identity===undefined?'bob':req.identity,rateKey:req.rateKey||actor,jobId:req.jobId||null};
   if(a.isolated){const result={status:423,body:{error:'API is isolated'},outcome:'isolated',before,after:before};this.store.event('traffic.blocked',apiId,actor,{request,...result});return result;}
   let detected=s.autoDetect?this.threat(a,request):null;
   const rk='gateway:'+apiId+':'+actor,t=Date.now(),rates=(this.rates.get(rk)||[]).filter(x=>t-x<1000);rates.push(t);this.rates.set(rk,rates);if(s.autoDetect&&rates.length>10)detected={type:'rate',severity:'Medium',reason:'More than 10 requests in one second from this authenticated operator to one API.'};
   let response;
   if(!detected){response=this.backend(a,request);if(s.autoDetect)detected=this.threat(a,request,response);}
   if(detected){const inc=this.incident(apiId,detected,request,actor);const result={status:403,body:{error:'Threat detected and blocked',incidentId:inc.id,reason:detected.type},outcome:'blocked',before,after:this.summary(this.api(apiId))};this.store.event('traffic.blocked',apiId,actor,{request,...result});return result;}
   if(request.method==='DELETE'&&response.status===200)this.save(a);
   const result={...response,outcome:response.status===200?(request.method==='DELETE'?'deleted':response.body.owner_id&&response.body.owner_id!==request.identity?'cross_user_data':response.body.private?'private_fields':'allowed'):'denied',before,after:this.summary(a),detectionEnabled:s.autoDetect};
   this.store.event('traffic.observed',apiId,actor,{request,...redact(result)});return result;
 }
 verify(a){const sample=structuredClone(a),probe=(identity,method='GET')=>this.backend(sample,{identity,method,ignoreRate:true});const owner=probe('alice'),foreign=probe('bob'),anon=probe(null),deletion=probe('bob','DELETE');const rates=Array.from({length:8},()=>this.backend(sample,{identity:'alice',rateKey:randomUUID().slice(0,0)+'verify-'+a.revision}));
   const checks={ownerRead:owner.status===200,foreignRead:foreign.status===403,anonymousRead:anon.status===401,foreignDelete:deletion.status===403,privateFieldsRemoved:owner.status===200&&!owner.body.private,rateControl:rates.some(r=>r.status===429),recordsRestored:a.records.length===2};
   return {passed:Object.values(checks).every(Boolean),checks,checkedAt:now(),statuses:{owner:owner.status,foreign:foreign.status,anonymous:anon.status,foreignDelete:deletion.status}};
 }
 repair(apiId,actor,incidentId=null){const a=this.api(apiId);if(!a.repairAllowed){a.isolated=true;this.save(a);this.store.event('repair.denied',apiId,actor,{reason:'No authority. API remains isolated.'});throw new Fault(403,'No repair authority; containment only');}const before=this.summary(a);a.isolated=true;this.save(a);this.store.event('repair.started',apiId,actor,{incidentId,before});
   a.secure=true;a.records=seed(apiId);a.revision++;this.save(a);const verification=this.verify(a);if(verification.passed)a.isolated=false;this.save(a);
   const result={id:randomUUID(),apiId,actor,incidentId,before,after:this.summary(a),verification,changes:['Require synthetic user authentication','Enforce owner authorization for reads and deletes','Remove private fields from response schema','Enable 5-request-per-second identity limit','Restore synthetic records from seed'],completedAt:now(),status:verification.passed?'repaired':'failed_isolated'};
   this.store.put('repair',result.id,result);
   for(const inc of this.store.list('incident',10000).filter(i=>i.apiId===apiId&&!['repaired'].includes(i.status))){inc.status=result.status;inc.after=result.after;inc.repair=result;inc.timeline.push({time:now(),stage:'patched',detail:result.changes.join('; ')},{time:now(),stage:verification.passed?'verified_and_reopened':'verification_failed_isolated',detail:verification});this.store.put('incident',inc.id,inc);}
   for(const f of this.store.list('finding',10000).filter(f=>f.apiId===apiId&&f.status==='open')){if(verification.passed){f.status='resolved';f.resolvedAt=now();this.store.put('finding',f.id,f);}}
   this.store.event('repair.completed',apiId,actor,result);return result;
 }
 action(apiIds,action,actor){const targets=ids(apiIds);if(!['repair','isolate','verify','release','reset','rollback','inspect'].includes(action))throw new Fault(400,'Unknown action');if(['repair','reset','rollback'].includes(action)&&targets.some(id=>!this.api(id).repairAllowed))throw new Fault(403,'Every selected API needs mutation authority. No changes applied.');return targets.map(id=>{if(action==='repair')return this.repair(id,actor);const a=this.api(id),before=this.summary(a);if(action==='inspect')return this.scan([id],actor,{respond:false});let verification=null;if(action==='isolate')a.isolated=true;if(['verify','release'].includes(action)){verification=this.verify(a);if(action==='release'&&verification.passed)a.isolated=false;}if(['reset','rollback'].includes(action)){a.secure=false;a.records=seed(id);a.isolated=action==='rollback';a.revision++;for(const k of this.rates.keys())if(k.includes(id))this.rates.delete(k);}this.save(a);const result={apiId:id,action,before,after:this.summary(a),verification};this.store.event('api.'+action,id,actor,result);return result;});}
 scan(apiIds,actor,{respond=true,budget=600}={}){const targets=ids(apiIds);if(this.scanRunning)throw new Fault(409,'A scan is already running');if(!Number.isInteger(budget)||budget<1||budget>1000)throw new Fault(400,'Budget must be 1–1000');this.scanRunning=true;const scan={id:randomUUID(),apiIds:targets,startedAt:now(),status:'running',requests:0,budget,findings:[]};this.store.put('scan',scan.id,scan);this.store.event('scan.started','',actor,{scanId:scan.id,apiIds:targets});
   try{for(const id of targets){const a=this.api(id),call=identity=>{if(scan.requests>=budget)throw new Error('Request budget exhausted');scan.requests++;return this.backend(structuredClone(a),{identity,ignoreRate:true});};const baseline=call('alice'),foreign=call('bob'),anon=call(null);const found=[];
     const add=(type,severity,reason,evidence,confidence='Confirmed')=>{const f={id:randomUUID(),scanId:scan.id,apiId:id,type,severity,confidence,reason,evidence:redact(evidence),status:'open',time:now(),reproduction:{method:'GET',path:`/lab/${id}/objects/1`,baselineIdentity:'alice',probeIdentity:type==='auth'?'anonymous':'bob'},remediation:'Use approved owner/authentication/response/rate controls, then verify before reopening.'};this.store.put('finding',f.id,f);scan.findings.push(f.id);found.push(f);this.store.event('finding.created',id,actor,{finding:f});};
     if(baseline.status===404)add('data_loss','Critical','Seeded object 1 is missing. A previous destructive action changed the sandbox.',{expectedRecords:2,actualRecords:a.records.length});
     else if(baseline.status!==200)throw new Error('Owner baseline unavailable; scan incomplete');
     if(baseline.status===200&&foreign.status===200&&foreign.body.owner_id==='alice'&&foreign.body.id===baseline.body.id)add('bola','High','Bob received Alice’s resource with the same stable ID and owner.',{baseline,probe:foreign});
     if(baseline.body.private)add('exposure','High','Response schema includes $.private.ssn, $.private.api_key and $.private.internal_notes.',{baseline});
     if(anon.status===200&&anon.body.owner_id==='alice')add('auth','High','Anonymous request retrieved an owner-marked private record.',{baseline,probe:anon});
     const rates=[];for(let i=0;i<8;i++){if(scan.requests>=budget)throw new Error('Request budget exhausted');scan.requests++;rates.push(this.backend(structuredClone(a),{identity:'alice',rateKey:scan.id}).status);}if(!rates.includes(429))add('rate','Info','No rate response in an eight-request bounded observation.',{statuses:rates},'Observation');
     if(respond&&this.settings().autoDetect&&found.some(f=>f.confidence==='Confirmed'))this.incident(id,{type:'scan_confirmed',severity:'High',reason:found.filter(f=>f.confidence==='Confirmed').length+' confirmed scan findings.'},{scanId:scan.id},actor,{source:'scanner',impact:'Underlying sandbox vulnerability or data loss confirmed by direct authorized probes.'});
   }scan.status='completed';}catch(e){scan.status='partial';scan.error=e.message;}finally{scan.finishedAt=now();this.scanRunning=false;this.store.put('scan',scan.id,scan);this.store.event('scan.completed','',actor,{scan});}return scan;
 }
 view(user){const all=user.role==='defender';return {workspace:'SentinelAPI live lab',version:2,seq:this.store.latest(),serverTime:now(),role:user.role,apis:APIS.map(id=>this.summary(this.api(id))),settings:all?this.settings():null,importedSpec:all?this.store.get('spec','current'):null,jobs:this.store.list('job',100).filter(j=>all||j.actor===user.name).map(j=>({...j,totalSteps:(j.steps||[]).length,steps:(j.steps||[]).slice(-12)})),incidents:all?this.store.list('incident',100):[],findings:all?this.store.list('finding',500):[],scans:all?this.store.list('scan',50):[],repairs:all?this.store.list('repair',100):[],events:this.store.events({limit:80}).filter(e=>all||e.actor===user.name),aiConfigured:Boolean(process.env.OPENAI_API_KEY&&process.env.AI_MODEL),aiProvider:process.env.OPENAI_API_KEY&&process.env.AI_MODEL?'OpenAI':'local rules'};}
 openapi(){const paths={};for(const id of APIS)for(const [suffix,methods]of [['objects',['get']],['objects/{id}',['get','delete']],['me',['get']],['search',['get']],['health',['get']]]){paths[`/lab/${id}/${suffix}`]=Object.fromEntries(methods.map(method=>[method,{description:'Synthetic private resources. Only the owner may access them.',security:[{operatorSession:[]}],parameters:[{name:'X-Synthetic-Identity',in:'header',schema:{type:'string',enum:['alice','bob','anonymous']}},...(suffix.includes('{id}')?[{name:'id',in:'path',required:true,schema:{type:'string',enum:['1','2']}}]:[]),...(suffix==='search'?[{name:'id',in:'query',schema:{type:'string',enum:['1','2']}}]:[])],responses:{200:{description:'Synthetic response'}}}]))}return {openapi:'3.0.3',info:{title:'SentinelAPI live sandbox',version:'2.0.0'},paths,components:{securitySchemes:{operatorSession:{type:'http',scheme:'bearer'}}}};}
}
