import http from 'node:http';
import { randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Store,redact } from './store.mjs';
import { Engine,Fault,ids,SCENARIOS,now } from './engine.mjs';
import { Auth } from './auth.mjs';
import { advise } from './advisor.mjs';

export async function createApp(options={}){
 const production=options.production??process.env.APP_ENV==='production',origins=options.origins||String(process.env.ALLOWED_ORIGINS||'http://127.0.0.1:5173,http://127.0.0.1:5174').split(',').map(s=>s.trim()).filter(Boolean);
 if(!origins.length||origins.some(o=>{try{const u=new URL(o);return u.origin!==o||!(u.protocol==='https:'||!production&&u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname));}catch{return true;}}))throw Error('ALLOWED_ORIGINS must be exact HTTPS site origins in production, without paths or trailing slashes');
 const store=new Store(options.dbPath||process.env.DATA_FILE||resolve('data/sentinel.sqlite')),engine=new Engine(store),auth=new Auth(store),clients=new Set(),workerKey=randomBytes(32).toString('hex');
 const users=options.users||[{name:process.env.DEFENDER_USER,password:process.env.DEFENDER_PASSWORD,role:'defender'},{name:process.env.ATTACKER_USER,password:process.env.ATTACKER_PASSWORD,role:'attacker'}];
 if(users.some(u=>!u.name||!u.password)||new Set(users.map(u=>u.name)).size!==users.length)throw Error('Configure distinct DEFENDER_USER / DEFENDER_PASSWORD and ATTACKER_USER / ATTACKER_PASSWORD');
 for(const u of users)await auth.provision(u.name,u.password,u.role);
 for(const old of store.db.prepare('SELECT name FROM users').all())if(!users.some(u=>u.name===old.name)){store.db.prepare('DELETE FROM sessions WHERE name=?').run(old.name);store.db.prepare('DELETE FROM users WHERE name=?').run(old.name);store.event('account.revoked','', 'system',{name:old.name,reason:'Account removed from configured operators'});}
 let baseURL='',closed=false,workerRunning=false,notifyTimer=null;const aiBusy=new Set(),requestRates=new Map();
 const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
 const requireDefender=u=>{if(u.role!=='defender')throw new Fault(403,'Defender permission required');};
 const readBody=async req=>{let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>1024*1024)throw new Fault(413,'Body exceeds 1 MiB');chunks.push(chunk);}try{const v=JSON.parse(Buffer.concat(chunks).toString()||'{}');if(!v||typeof v!=='object'||Array.isArray(v))throw Error();return v;}catch{throw new Fault(400,'Expected a JSON object');}};
 const allowedEvent=(e,u)=>u.role==='defender'||e.actor===u.name;
 function push(client,type,data,id){if(client.res.destroyed||client.res.writableLength>512000){client.res.end();clients.delete(client);return;}client.res.write(`${id?'id: '+id+'\n':''}event: ${type}\ndata: ${JSON.stringify(data)}\n\n`);}
 const onEvent=e=>{for(const c of clients)if(allowedEvent(e,c.user))push(c,'event',e,e.seq);if(!notifyTimer)notifyTimer=setTimeout(()=>{notifyTimer=null;for(const c of clients)push(c,'state',engine.view(c.user),store.latest());},20);};store.on('event',onEvent);
 const server=http.createServer(async(req,res)=>{
  const requestId=randomUUID();res.setHeader('X-Request-ID',requestId);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');res.setHeader('Vary','Origin');res.setHeader('X-Frame-Options','DENY');
  try{const origin=req.headers.origin;if(origin&&!origins.includes(origin))throw new Fault(403,'Origin is not allowed. Add the exact site URL to backend ALLOWED_ORIGINS.');if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type,Idempotency-Key,Last-Event-ID,X-Synthetic-Identity');res.setHeader('Access-Control-Max-Age','600');}
   if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}
   const url=new URL(req.url,'http://backend'),path=url.pathname;
   if(path==='/health'&&req.method==='GET')return json(res,{ok:true,service:'sentinel-live',version:'2.0.0',time:now()});
   if(path==='/auth/login'&&req.method==='POST'){const b=await readBody(req),result=await auth.login(b.username,b.password,req.socket.remoteAddress);store.event('session.login','',result.user.name,{role:result.user.role});return json(res,result);}
   let user;const supplied=req.headers['x-worker-key'];if(supplied&&supplied.length===workerKey.length&&timingSafeEqual(Buffer.from(supplied),Buffer.from(workerKey))){const job=store.get('job',String(req.headers['x-worker-job']));if(!job||job.status!=='running')throw new Fault(403,'Invalid worker job');user={name:job.actor,role:'attacker',worker:true,jobId:job.id,allowed:job.apiIds};}else user=auth.user(req.headers.authorization);
   const rateKey=user.name+':'+Math.floor(Date.now()/60000),count=(requestRates.get(rateKey)||0)+1;requestRates.set(rateKey,count);if(requestRates.size>500)requestRates.clear();if(count>1200)throw new Fault(429,'Operator request limit exceeded');
   if(user.worker&&!path.startsWith('/lab/'))throw new Fault(403,'Worker scope is limited to sandbox requests');
   if(path==='/auth/logout'&&req.method==='POST'){auth.logout(user);for(const c of clients)if(c.user.sessionHash===user.sessionHash)c.res.end();return json(res,{ok:true});}
   if(path==='/state'&&req.method==='GET')return json(res,engine.view(user));
   if(path.startsWith('/jobs/')&&req.method==='GET'){const job=store.get('job',path.slice(6));if(!job||user.role!=='defender'&&job.actor!==user.name)throw new Fault(404,'Simulation not found');return json(res,job);}
   if(path==='/events'&&req.method==='GET'){
    if(clients.size>=80||[...clients].filter(c=>c.user.name===user.name).length>=8)throw new Fault(429,'Too many live connections');
    const after=Number(url.searchParams.get('after')||req.headers['last-event-id']||0);if(!Number.isSafeInteger(after)||after<0)throw new Fault(400,'Invalid event cursor');
    res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders();req.socket.setTimeout(0);const client={res,user};clients.add(client);const missed=store.events({after,limit:500}).reverse();for(const e of missed)if(allowedEvent(e,user))push(client,'event',e,e.seq);push(client,'state',engine.view(user),store.latest());push(client,'connected',{time:now(),replayWindow:500});req.on('close',()=>clients.delete(client));return;
   }
   if(path==='/history'&&req.method==='GET'){const before=Number(url.searchParams.get('before')||Number.MAX_SAFE_INTEGER),kind=url.searchParams.get('kind')||'events',offset=Number(url.searchParams.get('offset')||0);if(!Number.isSafeInteger(before)||!Number.isInteger(offset)||offset<0)throw new Fault(400,'Invalid pagination');if(kind==='events'){const rows=store.events({before,limit:200});return json(res,{items:rows.filter(e=>allowedEvent(e,user)),nextBefore:rows.at(-1)?.seq||null});}if(!['job','incident','finding','repair','scan'].includes(kind))throw new Fault(400,'Unknown history kind');if(user.role!=='defender'&&kind!=='job')throw new Fault(403,'Defender permission required');const items=store.list(kind,200,offset).filter(x=>user.role==='defender'||x.actor===user.name);return json(res,{items,nextOffset:offset+200});}
   if(path==='/report'&&req.method==='GET'){requireDefender(user);const result={exportedAt:now(),scope:'Synthetic sandbox only',...engine.view(user)};res.setHeader('Content-Disposition','attachment; filename="sentinel-live-report.json"');return json(res,redact(result));}
   if(path==='/openapi.json'&&req.method==='GET')return json(res,engine.openapi());
   if(path.startsWith('/lab/')){
    const match=/^\/lab\/([a-z]+)\/(objects(?:\/([12]))?|search|me|health)$/.exec(path);if(!match)throw new Fault(404,'Unknown sandbox route');const apiId=match[1];if(user.worker&&!user.allowed.includes(apiId))throw new Fault(403,'API outside this job scope');if(!['GET','DELETE'].includes(req.method)||req.method==='DELETE'&&!match[3])throw new Fault(405,'Unsupported sandbox method');const identity=req.headers['x-synthetic-identity']||'anonymous';if(!['alice','bob','anonymous'].includes(identity))throw new Fault(400,'Unknown synthetic identity');const resource=match[2]==='objects'?'list':match[2].startsWith('objects/')?'objects':match[2];const id=match[3]||url.searchParams.get('id')||'1';if(!['1','2'].includes(id))throw new Fault(400,'Use a seeded object ID');const result=engine.request(apiId,{method:req.method,resource,id,identity:identity==='anonymous'?null:identity,jobId:user.jobId},user.name);return json(res,result,result.status);
   }
   if(req.method!=='POST')throw new Fault(404,'Endpoint not found');const data=await readBody(req);
   if(path==='/attacks'){
    const apiIds=ids(data.apiIds);if(!SCENARIOS.includes(data.scenario))throw new Fault(400,'Choose a supported scenario');const key=String(req.headers['idempotency-key']||'');if(!/^[a-zA-Z0-9_-]{10,100}$/.test(key))throw new Fault(400,'An Idempotency-Key is required');const prior=store.db.prepare('SELECT result FROM dedupe WHERE actor=? AND key=?').get(user.name,key);if(prior)return json(res,JSON.parse(prior.result),200);
    if(store.list('job',100).filter(j=>['queued','running'].includes(j.status)).length>=10)throw new Fault(429,'Simulation queue is full');const job={id:randomUUID(),actor:user.name,scenario:data.scenario,apiIds,status:'queued',steps:[],startedAt:now(),requests:0,blocked:0,succeeded:0};store.put('job',job.id,job);store.db.prepare('INSERT INTO dedupe VALUES(?,?,?)').run(user.name,key,JSON.stringify(job));store.event('simulation.queued','',user.name,{jobId:job.id,apiIds,scenario:job.scenario});setImmediate(work);return json(res,job,202);
   }
   if(path==='/attacks/cancel'){const job=store.get('job',data.id);if(!job||user.role!=='defender'&&job.actor!==user.name)throw new Fault(404,'Simulation not found');if(['queued','running'].includes(job.status)){job.cancelRequested=true;store.put('job',job.id,job);store.event('simulation.cancel_requested','',user.name,{jobId:job.id});}return json(res,job);}
   requireDefender(user);
   if(path==='/settings')return json(res,engine.updateSettings(data,user.name));
   if(path==='/authority'){engine.authority(data.apiIds,data.allowed,user.name);return json(res,{ok:true});}
   if(path==='/actions')return json(res,{results:engine.action(data.apiIds,data.action,user.name)});
   if(path==='/scans'){let scope=data.apiIds;if(data.useImported){const spec=store.get('spec','current');if(!spec?.scanApiIds?.length)throw new Fault(400,'Import a spec with registered GET /lab/<api>/objects/{id} operations first');scope=ids(data.apiIds).filter(id=>spec.scanApiIds.includes(id));if(!scope.length)throw new Fault(400,'Selection has no scannable APIs in the imported spec');}return json(res,engine.scan(scope,user.name,{budget:data.budget??600}),201);}
   if(path==='/spec/import'){let spec;try{spec=typeof data.spec==='string'?JSON.parse(data.spec):data.spec;}catch{throw new Fault(400,'Invalid JSON definition');}if(!spec||!(String(spec.openapi||'').startsWith('3.')||spec.swagger==='2.0')||!spec.paths||typeof spec.paths!=='object'||Object.keys(spec.paths).length>1000)throw new Fault(400,'Expected an OpenAPI 3 / Swagger 2 JSON definition with at most 1000 paths');const paths=Object.keys(spec.paths),accepted=paths.filter(p=>/^\/lab\/([a-z]+)\/(objects(?:\/\{id\})?|search|me|health)$/.test(p)&&engine.openapi().paths[p]);const result={title:String(spec.info?.title||'Imported spec').slice(0,100),paths:paths.length,executablePaths:accepted,scanApiIds:accepted.filter(p=>p.endsWith('/objects/{id}')&&spec.paths[p]?.get).map(p=>p.split('/')[2]),inventoryOnly:paths.length-accepted.length,importedAt:now()};store.put('spec','current',result);store.event('spec.imported','',user.name,result);return json(res,result);}
   if(path==='/advice'){const inc=store.get('incident',data.incidentId);if(!inc)throw new Fault(404,'Incident not found');if(aiBusy.size>=2||aiBusy.has(inc.id))throw new Fault(429,'Advice generation is already running');if(inc.advice&&Date.now()-Date.parse(inc.advice.generatedAt)<30000)return json(res,inc.advice);aiBusy.add(inc.id);try{const advice=await advise(inc,engine.api(inc.apiId));const latest=store.get('incident',inc.id);latest.advice=advice;store.put('incident',inc.id,latest);store.event('advice.generated',inc.apiId,user.name,{incidentId:inc.id,advice});return json(res,advice);}finally{aiBusy.delete(inc.id);}}
   throw new Fault(404,'Endpoint not found');
  }catch(e){if(!res.headersSent)json(res,{error:e instanceof Fault?e.message:'Request failed. Review server health and request ID.',requestId},e instanceof Fault?e.status:500);else res.end();if(!(e instanceof Fault))console.error(JSON.stringify({time:now(),requestId,type:e.name,message:'Unhandled request failure'}));}
 });
 server.requestTimeout=20000;server.headersTimeout=10000;server.keepAliveTimeout=5000;server.maxHeadersCount=40;server.maxConnections=200;
 server.on('clientError',(_err,socket)=>socket.end('HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n'));
 async function work(){if(workerRunning||closed)return;workerRunning=true;try{for(;;){let job=store.list('job',100).reverse().find(j=>j.status==='queued');if(!job)break;job.status='running';store.put('job',job.id,job);store.event('simulation.started','',job.actor,{jobId:job.id});
   try{for(const api of job.apiIds){const base=`/lab/${api}`;let plan=job.scenario==='chain'?[['GET','/me','bob'],['GET','/objects','bob'],['GET','/objects/1','bob'],['DELETE','/objects/1','bob']]:job.scenario==='rate'?Array.from({length:12},()=>['GET','/me','bob']):[[job.scenario==='delete'?'DELETE':'GET',job.scenario==='legitimate'?'/objects/2':'/objects/1',job.scenario==='auth'?'anonymous':job.scenario==='exposure'?'alice':'bob']];for(const [method,path,identity]of plan){if(store.get('job',job.id).cancelRequested||closed)throw new Error('cancelled');store.event('simulation.request_sent',api,job.actor,{jobId:job.id,method,path:base+path,identity});const r=await fetch(baseURL+base+path,{method,headers:{'X-Worker-Key':workerKey,'X-Worker-Job':job.id,'X-Synthetic-Identity':identity},signal:AbortSignal.timeout(5000)});const result=await r.json();const step={time:now(),apiId:api,method,path:base+path,identity,...redact(result)};job=store.get('job',job.id);job.steps.push(step);job.requests++;job.blocked+=Number([401,403,423,429].includes(r.status));job.succeeded+=Number(r.status===200);store.put('job',job.id,job);store.event('simulation.response',api,job.actor,{jobId:job.id,step});if(job.scenario!=='rate')await new Promise(r=>setTimeout(r,100));}}
   job.status='completed';}catch(e){job=store.get('job',job.id);job.status=e.message==='cancelled'?'cancelled':'failed';job.error=e.message==='cancelled'?'Cancelled before the next request':'Gateway request failed or timed out';}job.finishedAt=now();store.put('job',job.id,job);store.event('simulation.completed','',job.actor,{jobId:job.id,status:job.status,requests:job.requests,blocked:job.blocked});}
  }finally{workerRunning=false;}}
 const heartbeat=setInterval(()=>{for(const c of clients){const row=store.db.prepare('SELECT expires FROM sessions WHERE hash=?').get(c.user.sessionHash);if(!row||row.expires<Date.now()){push(c,'expired',{message:'Session ended'});c.res.end();clients.delete(c);}else c.res.write(': heartbeat '+Date.now()+'\n\n');}},15000);heartbeat.unref();
 const schedule=setInterval(()=>{const s=engine.settings();if(s.continuous&&Date.now()-(store.get('schedule','last')||0)>=s.intervalSeconds*1000){store.put('schedule','last',Date.now());try{engine.scan(s.scanIds,'scheduler');}catch{store.event('scan.schedule_failed','', 'system',{reason:'Scheduled scan could not start'});}}},1000);schedule.unref();
 return {server,store,engine,auth,clients,async listen(port=0,host='127.0.0.1'){await new Promise(r=>server.listen(port,host,r));baseURL='http://127.0.0.1:'+server.address().port;return baseURL;},async close(){closed=true;engine.close();clearInterval(heartbeat);clearInterval(schedule);clearTimeout(notifyTimer);store.off('event',onEvent);for(const c of clients)c.res.end();server.closeAllConnections();await new Promise(r=>server.close(r));for(let i=0;workerRunning&&i<60;i++)await new Promise(r=>setTimeout(r,100));store.close();}};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const app=await createApp();const host=process.env.APP_ENV==='production'?'0.0.0.0':'127.0.0.1';await app.listen(Number(process.env.PORT||9080),host);console.log('Sentinel live backend listening on port '+app.server.address().port);for(const sig of ['SIGTERM','SIGINT'])process.on(sig,async()=>{await app.close();process.exit(0);});}
